const assert = require('node:assert/strict')
const test = require('node:test')
const fs = require('node:fs')
const path = require('node:path')

test('fresh schema exposes hardened auth readiness and rejects missing RPCs', async (t) => {
  const { PGlite } = await import('@electric-sql/pglite')
  const { pgcrypto } = await import('@electric-sql/pglite/contrib/pgcrypto')
  const db = await PGlite.create({ extensions: { pgcrypto } })
  t.after(() => db.close())
  await db.exec('create role anon; create role authenticated; create role service_role bypassrls;')
  await db.exec(fs.readFileSync(path.resolve(__dirname, '../database/schema.sql'), 'utf8'))
  assert.equal((await db.query('select get_backend_readiness() as version')).rows[0].version, 27)
  for (const role of ['anon', 'authenticated']) {
    assert.equal((await db.query("select has_function_privilege($1,'public.issue_refresh_token(uuid,text,timestamptz)','execute') as allowed", [role])).rows[0].allowed, false)
    assert.equal((await db.query("select has_table_privilege($1,'public.refresh_tokens','select') as allowed", [role])).rows[0].allowed, false)
  }
  await db.exec('drop function public.revoke_refresh_token(text)')
  await assert.rejects(db.query('select get_backend_readiness()'), /dependencies are missing/)
})

test('026 upgrade revokes legacy tokens and reapplication preserves new sessions', async (t) => {
  const { PGlite } = await import('@electric-sql/pglite')
  const { pgcrypto } = await import('@electric-sql/pglite/contrib/pgcrypto')
  const db = await PGlite.create({ extensions: { pgcrypto } })
  t.after(() => db.close())
  const directory = path.resolve(__dirname, '../database')
  await db.exec('create role anon; create role authenticated; create role service_role bypassrls;')
  await db.exec(fs.readFileSync(path.join(directory, 'schema.sql'), 'utf8').split('create table if not exists public.refresh_tokens')[0])
  await db.exec(fs.readFileSync(path.join(directory, 'migrations/026_refresh_tokens.sql'), 'utf8'))
  const { rows } = await db.query("insert into roles(name) values ('Admin') returning id")
  const user = await db.query("insert into users(name,username,password_hash,role_id) values ('Test','upgrade','hash',$1) returning id", [rows[0].id])
  const userId = user.rows[0].id
  await db.query("insert into refresh_tokens(user_id,token_hash,expires_at) values ($1,repeat('a',64),now()+interval '1 hour')", [userId])
  const migration = fs.readFileSync(path.join(directory, 'migrations/027_harden_auth_sessions.sql'), 'utf8')
  await db.exec(migration)
  assert.equal((await db.query("select * from rotate_refresh_token(repeat('a',64),repeat('b',64))")).rows[0].outcome, 'invalid')
  await db.query("select issue_refresh_token($1,repeat('c',64),now()+interval '1 hour')", [userId])
  await db.exec(migration)
  assert.equal((await db.query("select * from rotate_refresh_token(repeat('c',64),repeat('d',64))")).rows[0].outcome, 'rotated')
  assert.equal((await db.query('select get_backend_readiness() as version')).rows[0].version, 27)
})
