const assert = require('node:assert/strict')
const test = require('node:test')
const fs = require('node:fs')
const path = require('node:path')
const { createAuthSessionDatabase } = require('./helpers/authSessionDatabase')

test('onboarding protects Admin and consumes setup exactly once with atomic audit', async (context) => {
  const { db, userId } = await createAuthSessionDatabase(context)
  await db.query('update users set must_change_password = false where id = $1', [userId])
  const migration = path.resolve(__dirname, '../database/migrations/029_account_onboarding.sql')
  assert.ok(fs.existsSync(migration), 'onboarding migration must exist')
  await db.exec(fs.readFileSync(migration, 'utf8'))
  await assert.rejects(db.query('update users set password_hash = null where id = $1', [userId]), /check constraint/)
  await db.exec(fs.readFileSync(migration, 'utf8'))
  await assert.rejects(db.query("update users set status='Inactive' where id=$1", [userId]), /Protected administrator/)
  await assert.rejects(db.query('delete from users where id=$1', [userId]), /Protected administrator/)
  await assert.rejects(db.exec("insert into users(name,username,password_hash,role_id) select 'Other','other','hash',id from roles where name='Admin'"))
  await db.exec("insert into roles(name) values ('Production Supervisor')")
  const tokenHash = 'a'.repeat(64)
  const added = await db.query('select add_invited_user($1,$2,$3,$4,$5,$6) as result', [userId, 'Operator', 'operator', 'operator@example.test', 'Production Supervisor', tokenHash])
  const invitedId = added.rows[0].result.id
  const before = await db.query('select password_hash,onboarding_state from users where id=$1', [invitedId])
  assert.deepEqual(before.rows[0], { password_hash: null, onboarding_state: 'Invited' })
  await assert.rejects(db.query('select issue_refresh_token($1,$2,now()+interval \'1 hour\')', [invitedId, 'b'.repeat(64)]))
  const hash = '$2b$10$' + 'a'.repeat(53)
  await db.exec("create function fail_setup_audit() returns trigger language plpgsql as $$ begin if new.action='PASSWORD_SETUP_COMPLETED' then raise exception 'audit unavailable'; end if; return new; end $$; create trigger fail_setup_audit before insert on audit_logs for each row execute function fail_setup_audit()")
  await assert.rejects(db.query('select complete_password_setup($1,$2)', [tokenHash, hash]), /audit unavailable/)
  assert.equal((await db.query('select used_at from password_setup_tokens where token_hash=$1', [tokenHash])).rows[0].used_at, null)
  assert.equal((await db.query('select password_hash from users where id=$1', [invitedId])).rows[0].password_hash, null)
  await db.exec('drop trigger fail_setup_audit on audit_logs')
  await db.query('select complete_password_setup($1,$2)', [tokenHash, hash])
  await assert.rejects(db.query('select complete_password_setup($1,$2)', [tokenHash, hash]), /Invalid or expired/)
  const after = await db.query('select password_hash,onboarding_state,must_change_password from users where id=$1', [invitedId])
  assert.deepEqual(after.rows[0], { password_hash: hash, onboarding_state: 'Ready', must_change_password: false })
  const audit = await db.query("select count(*)::int as count from audit_logs where entity_id=$1 and action='PASSWORD_SETUP_COMPLETED'", [invitedId])
  assert.equal(audit.rows[0].count, 1)
  const second = await db.query('select add_invited_user($1,$2,$3,$4,$5,$6) as result', [userId, 'Second', 'second', 'second@example.test', 'Production Supervisor', 'c'.repeat(64)])
  const secondId = second.rows[0].result.id
  await assert.rejects(db.query('select resend_user_invitation($1,$2,$3)', [userId, secondId, 'd'.repeat(64)]), /Wait one minute/)
  await db.query("update password_setup_tokens set created_at=now()-interval '2 minutes',expires_at=now()-interval '1 minute' where user_id=$1", [secondId])
  await assert.rejects(db.query('select complete_password_setup($1,$2)', ['c'.repeat(64), hash]), /Invalid or expired/)
  const directory = (await db.query("select list_user_accounts(1,1,'','Production Supervisor','','Expired','name','asc') as result")).rows[0].result
  assert.equal(directory.total, 1)
  assert.equal(directory.users[0].id, secondId)
  assert.equal(directory.summary.total, 3)
  assert.equal(Object.hasOwn(directory.users[0], 'password_hash'), false)
  await db.query('select resend_user_invitation($1,$2,$3)', [userId, secondId, 'd'.repeat(64)])
  await assert.rejects(db.query('select complete_password_setup($1,$2)', ['c'.repeat(64), hash]), /Invalid or expired/)
  await db.query("update users set status='Inactive' where id=$1", [secondId])
  await db.query("update users set status='Active' where id=$1", [secondId])
  await assert.rejects(db.query('select complete_password_setup($1,$2)', ['d'.repeat(64), hash]), /Invalid or expired/)
  await db.exec('set role anon')
  await assert.rejects(db.query('select complete_password_setup($1,$2)', [tokenHash, hash]), /permission denied/)
  await assert.rejects(db.query('select list_user_accounts()'), /permission denied/)
  await db.exec('reset role; set role authenticated')
  await assert.rejects(db.query('select * from password_setup_tokens'), /permission denied/)
})
